name: Running Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: "7.6.1"
        arguments: build -x test
    - name: Run tests
      run: gradle :test --tests 'ru.decahthuk.transactionhelperplugin.*'
